services:
  user-service:
    build: .
    depends_on:
      - user-db
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./:/app
  user-db:
    image: postgres
    volumes:
      - user-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}

volumes:
  user-data:

